In [1]:
import pandas as pd
import numpy as np

In [2]:
##data reading
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [3]:
df_train.head()

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
0,1,NaN,Afghanistan,33.0,65.0,2020-01-22,0.0,0.0
1,2,NaN,Afghanistan,33.0,65.0,2020-01-23,0.0,0.0
2,3,NaN,Afghanistan,33.0,65.0,2020-01-24,0.0,0.0
3,4,NaN,Afghanistan,33.0,65.0,2020-01-25,0.0,0.0
4,5,NaN,Afghanistan,33.0,65.0,2020-01-26,0.0,0.0

In [12]:
lst_countries=list(df_train['Country/Region'])
len(set(lst_countries))

163

In [242]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))

In [243]:
df_india=df_train.loc[df_train['Country/Region'] == 'India']

In [244]:
# df_india=sc.fit_transform(df_india)
df_india.tail()

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
7931,11869,NaN,India,21.0,78.0,2020-03-19,194.0,4.0
7932,11870,NaN,India,21.0,78.0,2020-03-20,244.0,5.0
7933,11871,NaN,India,21.0,78.0,2020-03-21,330.0,4.0
7934,11872,NaN,India,21.0,78.0,2020-03-22,396.0,7.0
7935,11873,NaN,India,21.0,78.0,2020-03-23,499.0,10.0

In [245]:
##Predicting on the basis of china and Itlay 
df_hub_china=df_train.loc[df_train['Province/State'] == 'Hubei']
df_it=df_train.loc[df_train['Country/Region'] == 'Italy']
df_it=df_train.loc[df_train['Country/Region'] == 'us']

In [230]:
df_hub_china

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
3720,5581,Hubei,China,30.9756,112.2707,2020-01-22,444.0,17.0
3721,5582,Hubei,China,30.9756,112.2707,2020-01-23,444.0,17.0
3722,5583,Hubei,China,30.9756,112.2707,2020-01-24,549.0,24.0
3723,5584,Hubei,China,30.9756,112.2707,2020-01-25,761.0,40.0
3724,5585,Hubei,China,30.9756,112.2707,2020-01-26,1058.0,52.0
3725,5586,Hubei,China,30.9756,112.2707,2020-01-27,1423.0,76.0
3726,5587,Hubei,China,30.9756,112.2707,2020-01-28,3554.0,125.0
3727,5588,Hubei,China,30.9756,112.2707,2020-01-29,3554.0,125.0
3728,5589,Hubei,China,30.9756,112.2707,2020-01-30,4903.0,162.0
3729,5590,Hubei,China,30.9756,112.2707,2020-01-31,5806.0,204.0
3730,5591,Hubei,China,30.9756,112.2707,2020-02-01,7153.0,249.0
3731,5592,Hubei,China,30.9756,112.2707,2020-02-02,11177.0,350.0
3732,5593,Hubei,China,30.9756,112.2707,2020-02-03,13522.0,414.0
3733,5594,Hubei,China,30.9756,112.2707,2020-02-04,16678.0,479.0
3734,5595,Hubei,China,30.9756,112.2707,2020-02-05,19665.0,549.0
3735,5596,Hubei,China,30.9756,112.2707,2020-02-06,22112.0,618.0
3736,5597,Hubei,China,30.9756,112.2707,2020-02-07,24953.0,699.0
3737,5598,Hubei,China,30.9756,112.2707,2020-02-08,27100.0,780.0
3738,5599,Hubei,China,30.9756,112.2707,2020-02-09,29631.0,871.0
3739,5600,Hubei,China,30.9756,112.2707,2020-02-10,31728.0,974.0
3740,5601,Hubei,China,30.9756,112.2707,2020-02-11,33366.0,1068.0
3741,5602,Hubei,China,30.9756,112.2707,2020-02-12,33366.0,1068.0
3742,5603,Hubei,China,30.9756,112.2707,2020-02-13,48206.0,1310.0
3743,5604,Hubei,China,30.9756,112.2707,2020-02-14,54406.0,1457.0
3744,5605,Hubei,China,30.9756,112.2707,2020-02-15,56249.0,1596.0
3745,5606,Hubei,China,30.9756,112.2707,2020-02-16,58182.0,1696.0
3746,5607,Hubei,China,30.9756,112.2707,2020-02-17,59989.0,1789.0
3747,5608,Hubei,China,30.9756,112.2707,2020-02-18,61682.0,1921.0
3748,5609,Hubei,China,30.9756,112.2707,2020-02-19,62031.0,2029.0
3749,5610,Hubei,China,30.9756,112.2707,2020-02-20,62442.0,2144.0
...,...,...,...,...,...,...,...,...
3752,5613,Hubei,China,30.9756,112.2707,2020-02-23,64084.0,2346.0
3753,5614,Hubei,China,30.9756,112.2707,2020-02-24,64287.0,2495.0
3754,5615,Hubei,China,30.9756,112.2707,2020-02-25,64786.0,2563.0
3755,5616,Hubei,China,30.9756,112.2707,2020-02-26,65187.0,2615.0
3756,5617,Hubei,China,30.9756,112.2707,2020-02-27,65596.0,2641.0
3757,5618,Hubei,China,30.9756,112.2707,2020-02-28,65914.0,2682.0
3758,5619,Hubei,China,30.9756,112.2707,2020-02-29,66337.0,2727.0
3759,5620,Hubei,China,30.9756,112.2707,2020-03-01,66907.0,2761.0
3760,5621,Hubei,China,30.9756,112.2707,2020-03-02,67103.0,2803.0
3761,5622,Hubei,China,30.9756,112.2707,2020-03-03,67217.0,2835.0
3762,5623,Hubei,China,30.9756,112.2707,2020-03-04,67332.0,2871.0
3763,5624,Hubei,China,30.9756,112.2707,2020-03-05,67466.0,2902.0
3764,5625,Hubei,China,30.9756,112.2707,2020-03-06,67592.0,2931.0
3765,5626,Hubei,China,30.9756,112.2707,2020-03-07,67666.0,2959.0
3766,5627,Hubei,China,30.9756,112.2707,2020-03-08,67707.0,2986.0
3767,5628,Hubei,China,30.9756,112.2707,2020-03-09,67743.0,3008.0
3768,5629,Hubei,China,30.9756,112.2707,2020-03-10,67760.0,3024.0
3769,5630,Hubei,China,30.9756,112.2707,2020-03-11,67773.0,3046.0
3770,5631,Hubei,China,30.9756,112.2707,2020-03-12,67781.0,3056.0
3771,5632,Hubei,China,30.9756,112.2707,2020-03-13,67786.0,3062.0
3772,5633,Hubei,China,30.9756,112.2707,2020-03-14,67790.0,3075.0
3773,5634,Hubei,China,30.9756,112.2707,2020-03-15,67794.0,3085.0
3774,5635,Hubei,China,30.9756,112.2707,2020-03-16,67798.0,3099.0
3775,5636,Hubei,China,30.9756,112.2707,2020-03-17,67799.0,3111.0
3776,5637,Hubei,China,30.9756,112.2707,2020-03-18,67800.0,3122.0
3777,5638,Hubei,China,30.9756,112.2707,2020-03-19,67800.0,3130.0
3778,5639,Hubei,China,30.9756,112.2707,2020-03-20,67800.0,3133.0
3779,5640,Hubei,China,30.9756,112.2707,2020-03-21,67800.0,3139.0
3780,5641,Hubei,China,30.9756,112.2707,2020-03-22,67800.0,3144.0
3781,5642,Hubei,China,30.9756,112.2707,2020-03-23,67800.0,3153.0

In [102]:
# cc_it=list(df_it[30:62])
# # cc_us=list()
# cc_it
df_it.iloc[30:62,:]

Empty DataFrame
Columns: [Id, Province/State, Country/Region, Lat, Long, Date, ConfirmedCases, Fatalities]
Index: []

In [246]:
training_set=df_hub_china.iloc[:,6:7].values
# training_set=np.array(training_set)
final_china=sc.fit_transform(training_set)
# final_china)
fatal=list(df_hub_china['Fatalities'])
training_set.shape

(62, 1)

In [247]:
final_china

array([[0.        ],
       [0.        ],
       [0.00155888],
       [0.00470634],
       [0.00911574],
       [0.01453471],
       [0.04617258],
       [0.04617258],
       [0.06620049],
       [0.07960687],
       [0.09960508],
       [0.15934735],
       [0.19416236],
       [0.24101788],
       [0.28536433],
       [0.32169369],
       [0.36387256],
       [0.39574797],
       [0.43332443],
       [0.46445751],
       [0.48877606],
       [0.48877606],
       [0.70909793],
       [0.80114615],
       [0.82850822],
       [0.85720648],
       [0.88403409],
       [0.90916919],
       [0.91435061],
       [0.92045252],
       [0.92371875],
       [0.94483045],
       [0.94483045],
       [0.94784429],
       [0.95525269],
       [0.96120613],
       [0.96727834],
       [0.97199952],
       [0.97827959],
       [0.98674209],
       [0.989652  ],
       [0.9913445 ],
       [0.99305184],
       [0.99504127],
       [0.99691193],
       [0.99801057],
       [0.99861928],
       [0.99915375],
       [0.99940614],
       [0.99959914],
       [0.99971792],
       [0.99979215],
       [0.99985154],
       [0.99991092],
       [0.99997031],
       [0.99998515],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ]])

In [248]:
##First predicting the confirmed cases

x_train=[]
y_train=[]
for i in range(19,62):
    x_train.append(final_china[i-19:i])
    y_train.append(final_china[i,0])

In [197]:
x_train.shape

AttributeError: 'list' object has no attribute 'shape'

In [249]:
# x_train[0][-1]
# y_train[0]

x_train,y_train=np.array(x_train),np.array(y_train)

# y_train=sc.fit_transform(y_train.reshape(-1,1))
# x_train=sc.fit_transform(x_train)

In [250]:
x_train.shape

(43, 19, 1)

In [251]:
x_train=np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

In [201]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [202]:
regressor=Sequential()
#1st layer
regressor.add(LSTM(units=60,return_sequences=True,input_shape=(x_train.shape[1],1)))
#2nd layer
regressor.add(LSTM(units=60,return_sequences=True))
#3rd layer
regressor.add(LSTM(units=60,return_sequences=True))
#4th layer
regressor.add(LSTM(units=60,return_sequences=True))
#5th layer
regressor.add(LSTM(units=60))
#o/p layer
regressor.add(Dense(units=1))

In [203]:
regressor.compile(optimizer='adam',loss='mean_squared_error')
regressor.fit(x_train,y_train,epochs=100,batch_size=20)

Train on 43 samples
Epoch 1/100
43/43 [==============================] - 5s 117ms/sample - loss: 0.8018
Epoch 2/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.3668
Epoch 3/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.1486
Epoch 4/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0501
Epoch 5/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0626
Epoch 6/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0719
Epoch 7/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0244
Epoch 8/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0161
Epoch 9/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0291
Epoch 10/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0114
Epoch 11/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0099
Epoch 12/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0137
Epoch 13/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0088
Epoch 14/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0064
Epoch 15/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0091
Epoch 16/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0082
Epoch 17/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0061
Epoch 18/100
43/43 [==============================] - 0s 6ms/sample - loss: 0.0060
Epoch 19/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0061
Epoch 20/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0058
Epoch 21/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0063
Epoch 22/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 23/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0065
Epoch 24/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0065
Epoch 25/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0057
Epoch 26/100
43/43 [==============================] - 0s 6ms/sample - loss: 0.0069
Epoch 27/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0063
Epoch 28/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0059
Epoch 29/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0065
Epoch 30/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0063
Epoch 31/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0057
Epoch 32/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0066
Epoch 33/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0065
Epoch 34/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0058
Epoch 35/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0063
Epoch 36/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0061
Epoch 37/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0058
Epoch 38/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0065
Epoch 39/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0060
Epoch 40/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0061
Epoch 41/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0057
Epoch 42/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0060
Epoch 43/100
43/43 [==============================] - 0s 7ms/sample - loss: 0.0061
Epoch 44/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 45/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 46/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0057
Epoch 47/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0056
Epoch 48/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0058
Epoch 49/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0063
Epoch 50/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0057
Epoch 51/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0069
Epoch 52/100
43/43 [==============================] - 0s 8ms/sample - loss: 0.0063
Epoch 53/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 54/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0064
Epoch 55/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0057
Epoch 56/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0059
Epoch 57/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0059
Epoch 58/100
43/43 [==============================] - 0s 8ms/sample - loss: 0.0054
Epoch 59/100
43/43 [==============================] - 0s 6ms/sample - loss: 0.0063
Epoch 60/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0063
Epoch 61/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0055
Epoch 62/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0062
Epoch 63/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0058
Epoch 64/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0056
Epoch 65/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0054
Epoch 66/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0058
Epoch 67/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0059
Epoch 68/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0053
Epoch 69/100
43/43 [==============================] - 0s 7ms/sample - loss: 0.0055
Epoch 70/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0054
Epoch 71/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0054
Epoch 72/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0052
Epoch 73/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 74/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0054
Epoch 75/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0051
Epoch 76/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0053
Epoch 77/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0057
Epoch 78/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0051
Epoch 79/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0066
Epoch 80/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0059
Epoch 81/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0052
Epoch 82/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0054
Epoch 83/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0050
Epoch 84/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0057
Epoch 85/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0054
Epoch 86/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0056
Epoch 87/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0048
Epoch 88/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0060
Epoch 89/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0046
Epoch 90/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0076
Epoch 91/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0050
Epoch 92/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0061
Epoch 93/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0052
Epoch 94/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0055
Epoch 95/100
43/43 [==============================] - 0s 5ms/sample - loss: 0.0046
Epoch 96/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0054
Epoch 97/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0045
Epoch 98/100
43/43 [==============================] - 0s 3ms/sample - loss: 0.0058
Epoch 99/100

43/43 [==============================] - 0s 4ms/sample - loss: 0.0044
Epoch 100/100
43/43 [==============================] - 0s 4ms/sample - loss: 0.0053

In [51]:
x_train.shape

(43, 19, 1)

In [264]:
final_df=df_india.loc[df_india['ConfirmedCases']>0]
final_df

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
7882,11820,NaN,India,21.0,78.0,2020-01-30,1.0,0.0
7883,11821,NaN,India,21.0,78.0,2020-01-31,1.0,0.0
7884,11822,NaN,India,21.0,78.0,2020-02-01,1.0,0.0
7885,11823,NaN,India,21.0,78.0,2020-02-02,2.0,0.0
7886,11824,NaN,India,21.0,78.0,2020-02-03,3.0,0.0
7887,11825,NaN,India,21.0,78.0,2020-02-04,3.0,0.0
7888,11826,NaN,India,21.0,78.0,2020-02-05,3.0,0.0
7889,11827,NaN,India,21.0,78.0,2020-02-06,3.0,0.0
7890,11828,NaN,India,21.0,78.0,2020-02-07,3.0,0.0
7891,11829,NaN,India,21.0,78.0,2020-02-08,3.0,0.0
7892,11830,NaN,India,21.0,78.0,2020-02-09,3.0,0.0
7893,11831,NaN,India,21.0,78.0,2020-02-10,3.0,0.0
7894,11832,NaN,India,21.0,78.0,2020-02-11,3.0,0.0
7895,11833,NaN,India,21.0,78.0,2020-02-12,3.0,0.0
7896,11834,NaN,India,21.0,78.0,2020-02-13,3.0,0.0
7897,11835,NaN,India,21.0,78.0,2020-02-14,3.0,0.0
7898,11836,NaN,India,21.0,78.0,2020-02-15,3.0,0.0
7899,11837,NaN,India,21.0,78.0,2020-02-16,3.0,0.0
7900,11838,NaN,India,21.0,78.0,2020-02-17,3.0,0.0
7901,11839,NaN,India,21.0,78.0,2020-02-18,3.0,0.0
7902,11840,NaN,India,21.0,78.0,2020-02-19,3.0,0.0
7903,11841,NaN,India,21.0,78.0,2020-02-20,3.0,0.0
7904,11842,NaN,India,21.0,78.0,2020-02-21,3.0,0.0
7905,11843,NaN,India,21.0,78.0,2020-02-22,3.0,0.0
7906,11844,NaN,India,21.0,78.0,2020-02-23,3.0,0.0
7907,11845,NaN,India,21.0,78.0,2020-02-24,3.0,0.0
7908,11846,NaN,India,21.0,78.0,2020-02-25,3.0,0.0
7909,11847,NaN,India,21.0,78.0,2020-02-26,3.0,0.0
7910,11848,NaN,India,21.0,78.0,2020-02-27,3.0,0.0
7911,11849,NaN,India,21.0,78.0,2020-02-28,3.0,0.0
7912,11850,NaN,India,21.0,78.0,2020-02-29,3.0,0.0
7913,11851,NaN,India,21.0,78.0,2020-03-01,3.0,0.0
7914,11852,NaN,India,21.0,78.0,2020-03-02,5.0,0.0
7915,11853,NaN,India,21.0,78.0,2020-03-03,5.0,0.0
7916,11854,NaN,India,21.0,78.0,2020-03-04,28.0,0.0
7917,11855,NaN,India,21.0,78.0,2020-03-05,30.0,0.0
7918,11856,NaN,India,21.0,78.0,2020-03-06,31.0,0.0
7919,11857,NaN,India,21.0,78.0,2020-03-07,34.0,0.0
7920,11858,NaN,India,21.0,78.0,2020-03-08,39.0,0.0
7921,11859,NaN,India,21.0,78.0,2020-03-09,43.0,0.0
7922,11860,NaN,India,21.0,78.0,2020-03-10,56.0,0.0
7923,11861,NaN,India,21.0,78.0,2020-03-11,62.0,1.0
7924,11862,NaN,India,21.0,78.0,2020-03-12,73.0,1.0
7925,11863,NaN,India,21.0,78.0,2020-03-13,82.0,2.0
7926,11864,NaN,India,21.0,78.0,2020-03-14,102.0,2.0
7927,11865,NaN,India,21.0,78.0,2020-03-15,113.0,2.0
7928,11866,NaN,India,21.0,78.0,2020-03-16,119.0,2.0
7929,11867,NaN,India,21.0,78.0,2020-03-17,142.0,3.0
7930,11868,NaN,India,21.0,78.0,2020-03-18,156.0,3.0
7931,11869,NaN,India,21.0,78.0,2020-03-19,194.0,4.0
7932,11870,NaN,India,21.0,78.0,2020-03-20,244.0,5.0
7933,11871,NaN,India,21.0,78.0,2020-03-21,330.0,4.0
7934,11872,NaN,India,21.0,78.0,2020-03-22,396.0,7.0
7935,11873,NaN,India,21.0,78.0,2020-03-23,499.0,10.0

In [266]:
dataset_total=pd.concat((df_hub_china['ConfirmedCases'],final_df['ConfirmedCases']),axis=0)
dataset_total

3720      444.0
3721      444.0
3722      549.0
3723      761.0
3724     1058.0
3725     1423.0
3726     3554.0
3727     3554.0
3728     4903.0
3729     5806.0
3730     7153.0
3731    11177.0
3732    13522.0
3733    16678.0
3734    19665.0
3735    22112.0
3736    24953.0
3737    27100.0
3738    29631.0
3739    31728.0
3740    33366.0
3741    33366.0
3742    48206.0
3743    54406.0
3744    56249.0
3745    58182.0
3746    59989.0
3747    61682.0
3748    62031.0
3749    62442.0
         ...
7906        3.0
7907        3.0
7908        3.0
7909        3.0
7910        3.0
7911        3.0
7912        3.0
7913        3.0
7914        5.0
7915        5.0
7916       28.0
7917       30.0
7918       31.0
7919       34.0
7920       39.0
7921       43.0
7922       56.0
7923       62.0
7924       73.0
7925       82.0
7926      102.0
7927      113.0
7928      119.0
7929      142.0
7930      156.0
7931      194.0
7932      244.0
7933      330.0
7934      396.0
7935      499.0
Name: ConfirmedCases, Length: 116, dtype: float64

In [267]:
inputs=dataset_total[len(dataset_total)-len(df_india)-19:].values
inputs=inputs.reshape(-1,1)
inputs.shape
inputs=sc.transform(inputs)

In [269]:
inputs

array([[ 9.61206129e-01],
       [ 9.67278342e-01],
       [ 9.71999525e-01],
       [ 9.78279589e-01],
       [ 9.86742087e-01],
       [ 9.89651998e-01],
       [ 9.91344498e-01],
       [ 9.93051844e-01],
       [ 9.95041273e-01],
       [ 9.96911931e-01],
       [ 9.98010571e-01],
       [ 9.98619277e-01],
       [ 9.99153750e-01],
       [ 9.99406141e-01],
       [ 9.99599145e-01],
       [ 9.99717917e-01],
       [ 9.99792149e-01],
       [ 9.99851535e-01],
       [ 9.99910921e-01],
       [ 9.99970307e-01],
       [ 9.99985154e-01],
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [-6.57699388e-03],
       [-6.57699388e-03],
       [-6.57699388e-03],
       [-6.56214740e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.54730091e-03],
       [-6.51760793e-03],
       [-6.51760793e-03],
       [-6.17613873e-03],
       [-6.14644575e-03],
       [-6.13159926e-03],
       [-6.08705980e-03],
       [-6.01282737e-03],
       [-5.95344142e-03],
       [-5.76043708e-03],
       [-5.67135816e-03],
       [-5.50804680e-03],
       [-5.37442841e-03],
       [-5.07749866e-03],
       [-4.91418730e-03],
       [-4.82510838e-03],
       [-4.48363917e-03],
       [-4.27578835e-03],
       [-3.71162183e-03],
       [-2.96929746e-03],
       [-1.69249955e-03],
       [-7.12631391e-04],
       [ 8.16556803e-04]])

In [271]:
x_test=inputs[-19:]
# for i in range()
len(x_test)

19

In [228]:
# len(cc_ind[-20:])
# cc_ind=cc_ind[-19:]
cc_in.shape

(19, 1)

In [218]:
# print(cc_ind)
cc_in=np.array(cc_in)
# cc_ind
cc_in=np.reshape(cc_ind,(cc_in.shape[0],19,1))

ValueError: cannot reshape array of size 19 into shape (19,19,1)

In [215]:
cc_ind

array([[[ 30.],
        [ 31.],
        [ 34.],
        [ 39.],
        [ 43.],
        [ 56.],
        [ 62.],
        [ 73.],
        [ 82.],
        [102.],
        [113.],
        [119.],
        [142.],
        [156.],
        [194.],
        [244.],
        [330.],
        [396.],
        [499.]]])

In [273]:
x_test=x_test.reshape(1,19,1)

predict=regressor.predict(x_test)

In [277]:
final=sc.inverse_transform(predict[0].reshape(-1,1))

In [278]:
final

array([[41897.99]], dtype=float32)